// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.14.0
// source: Career.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CareerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx         int32 `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	ConditionId int32 `protobuf:"varint,2,opt,name=conditionId,proto3" json:"conditionId,omitempty"`
	Count       int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Time        int64 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *CareerData) Reset() {
	*x = CareerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Career_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerData) ProtoMessage() {}

func (x *CareerData) ProtoReflect() protoreflect.Message {
	mi := &file_Career_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerData.ProtoReflect.Descriptor instead.
func (*CareerData) Descriptor() ([]byte, []int) {
	return file_Career_proto_rawDescGZIP(), []int{0}
}

func (x *CareerData) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *CareerData) GetConditionId() int32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *CareerData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CareerData) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_Career_proto protoreflect.FileDescriptor

var file_Career_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x6a, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x69, 0x64, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Career_proto_rawDescOnce sync.Once
	file_Career_proto_rawDescData = file_Career_proto_rawDesc
)

func file_Career_proto_rawDescGZIP() []byte {
	file_Career_proto_rawDescOnce.Do(func() {
		file_Career_proto_rawDescData = protoimpl.X.CompressGZIP(file_Career_proto_rawDescData)
	})
	return file_Career_proto_rawDescData
}

var file_Career_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Career_proto_goTypes = []interface{}{
	(*CareerData)(nil), // 0: main.CareerData
}
var file_Career_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Career_proto_init() }
func file_Career_proto_init() {
	if File_Career_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Career_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Career_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Career_proto_goTypes,
		DependencyIndexes: file_Career_proto_depIdxs,
		MessageInfos:      file_Career_proto_msgTypes,
	}.Build()
	File_Career_proto = out.File
	file_Career_proto_rawDesc = nil
	file_Career_proto_goTypes = nil
	file_Career_proto_depIdxs = nil
}
